### ISSUE TITLE
Crash on API 15

### ISSUE THREAD

**Issue by EmmanuelMess** [jahirfiquitiva/FABsMenu#33] opened 2018-03-30 17:26 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of FABsMenu.

### Device/dashboard info:
 - FABsMenu version: `1.1.2`
 - Android version: `API 15`
 - Device Manufacturer: `AVD`
 - Device Name: `Nexus One`
```java
floatingActionButton = findViewById(R.id.fabs_menu);
floatingActionButton.getMenuButton().setBackgroundColor(colorAccent);
```

```Gradle
W/System.err: android.content.res.Resources$NotFoundException: File res/drawable/ic_add_white_24dp.xml from drawable resource ID #0x7f080072
W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:1928)
                  at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                  at jahirfiquitiva.libs.fabsmenu.FABsMenu.init(FABsMenu.java:152)
                  at jahirfiquitiva.libs.fabsmenu.FABsMenu.<init>(FABsMenu.java:106)
                  at java.lang.reflect.Constructor.constructNative(Native Method)
                  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                  at android.view.LayoutInflater.createView(LayoutInflater.java:586)
                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
                  at android.view.LayoutInflater.parseInclude(LayoutInflater.java:823)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:729)
                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                  at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                  at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:278)
                  at android.app.Activity.performCreate(Activity.java:4466)
                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
                  at android.app.ActivityThread.access$600(ActivityThread.java:123)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
                  at android.os.Handler.dispatchMessage(Handler.java:99)
                  at android.os.Looper.loop(Looper.java:137)
                  at android.app.ActivityThread.main(ActivityThread.java:4424)
                  at java.lang.reflect.Method.invokeNative(Native Method)
                  at java.lang.reflect.Method.invoke(Method.java:511)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                  at dalvik.system.NativeStart.main(Native Method)
              Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #0: invalid drawable tag vector
                  at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:863)
                  at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:1925)
              	... 31 more

E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.NullPointerException
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
                      at android.app.ActivityThread.access$600(ActivityThread.java:123)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4424)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.NullPointerException
                      at com.amaze.filemanager.activities.MainActivity.initialiseFab(MainActivity.java:1416)
                      at com.amaze.filemanager.activities.MainActivity.onCreate(MainActivity.java:290)
                      at android.app.Activity.performCreate(Activity.java:4466)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981) 
                      at android.app.ActivityThread.access$600(ActivityThread.java:123) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4424) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by jahirfiquitiva** [comment] 2018-03-31 00:41
Duplicate of #27

**Comment by jahirfiquitiva** [comment] 2018-03-31 00:42
Please try version `1.1.3`

**Closed by jahirfiquitiva** 2018-03-31 00:41 UTC
Labels: duplicate

**Comment by EmmanuelMess** [comment] 2018-04-01 15:50
Sorry for duplicating, I though the other crash was fixed and this one was different. It works now, thanks!
