### ISSUE TITLE
FAB margins are wrong on pre-lollipop

### ISSUE THREAD

**Issue by leinardi** [jahirfiquitiva/FABsMenu#32] opened 2018-03-23 17:36 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of FABsMenu.

### Device/dashboard info:
 - FABsMenu version: `1.1.2`
 - Android version: `API 16 to 27`
 - Device Manufacturer: `Google`
 - Device Name: `Emulator`

### Reproduction Steps

1. Build the sample app 
2. Run it on API < 21 (fix for the crash available [here](https://github.com/jahirfiquitiva/FABsMenu/pull/29))
3. Click on the FAB 

### Expected Result
All the FABs are using the same margin on every API level

### Actual Result
API < 21 have different margins than API >= 21

![image](https://user-images.githubusercontent.com/273338/37844752-095bb8ce-2ec9-11e8-81f0-8e9087e36d7e.png) ![image](https://user-images.githubusercontent.com/273338/37844763-0f120034-2ec9-11e8-90d4-3a33676d6665.png)

**Comment by EmmanuelMess** [comment] 2018-04-01 15:51
Can replicate in `1.1.3`.

**Comment by jahirfiquitiva** [comment] 2018-04-01 16:04
@EmmanuelMess 
The issue is still open, so it for sure hasn't been fixed. When fixed, I will close the issue.

Sorry for this taking too long, but I'm quite busy with University and work 😕

**Comment by jahirfiquitiva** [comment] 2018-05-02 20:45
Probably related [to this](https://github.com/leinardi/FloatingActionButtonSpeedDial/issues/30).

Anyways, I'm [deprecating this library](https://github.com/jahirfiquitiva/FABsMenu/#deprecated). Sorry

**Closed by jahirfiquitiva** 2018-05-02 20:45 UTC
Labels: accepted, bug, help wanted, high priority
