### ISSUE TITLE
FABsMenu loses margins when expand direction is changed programmatically

### ISSUE THREAD

**Issue by RealFeeling** [jahirfiquitiva/FABsMenu#7] opened 2017-08-01 03:28 UTC
My fabsMenu default ExpandDirection is UP. But when I change it using fabMenu.setExpandDirection(FABsMenu.EXPAND_LEFT);.
fabMenu.toggle();
The fabsMenu changes its positions and loses its margins

**Comment by jahirfiquitiva** [comment] 2017-08-01 03:35
@RealFeeling 

1. Can you please check your issue spelling just so I avoid confussions?
2. Can you please record a video/gif showing the issue?

**Comment by RealFeeling** [comment] 2017-08-01 04:07
Ok, thx!

My layout xml:

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:fab="http://schemas.android.com/apk/res-auto"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

    <Button
        android:id="@+id/btn_test"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Test"
        />

    <jahirfiquitiva.libs.fabsmenu.FABsMenuLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

        <jahirfiquitiva.libs.fabsmenu.FABsMenu
                android:id="@+id/fabs_menu"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom|end"
                android:clipChildren="false"
                fab:fab_menuMargins="40dp"
                fab:fab_moreButtonPlusIcon="@drawable/ic_plus"
                fab:fab_moreButtonBackgroundColor="@color/pink"
                fab:fab_moreButtonRippleColor="@color/pink_pressed"
                fab:fab_moreButtonSize="normal"
                fab:fab_labelsPosition="left">

        </jahirfiquitiva.libs.fabsmenu.FABsMenu>
    </jahirfiquitiva.libs.fabsmenu.FABsMenuLayout>

</RelativeLayout>

java file : 

public class MainActivity extends Activity {

    private FABsMenu fabMenu;
    private TitleFAB buttonOne, buttonTwo, buttonThree, buttonFour, buttonFive, buttonSix, buttonSeven;
    private int FAB_MENU_STATE;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);

        setContentView(R.layout.activity_main);

        Button button = findViewById(R.id.btn_test);

        fabMenu = findViewById(R.id.fabs_menu);
        fabMenu.setMenuUpdateListener(new FABsMenu.OnFABsMenuUpdateListener() {
            @Override
            public void onMenuClicked() {
                setUpFabMenuItem(true);
            }

            @Override
            public void onMenuExpanded() {
                showToast("The menu has been expanded!");
            }

            @Override
            public void onMenuCollapsed() {
                showToast("The menu has been collapsed!");
            }
        });

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                setUpFabMenuItem(false);
            }
        });
    }

    private void showToast(String text) {
        Toast.makeText(this, text, Toast.LENGTH_SHORT).show();
    }

    private void setUpFabMenuItem(boolean isCreate) {

        if (fabMenu.isExpanded()) {
            fabMenu.collapse();
            return;
        }

        if (isCreate && FAB_MENU_STATE != 1) {
            FAB_MENU_STATE = 1;

            if (fabMenu.getButtonsCount() > 1) {
                fabMenu.removeButton(buttonFive);
                fabMenu.removeButton(buttonSix);
                fabMenu.removeButton(buttonSeven);
            }

            fabMenu.setExpandDirection(FABsMenu.EXPAND_UP);

            buttonOne = new TitleFAB(this);
            buttonOne.setTitle("buttonOne");
            buttonOne.setBackgroundColor(ContextCompat.getColor(this, R.color.colorAccent));
            buttonOne.setImageResource(R.drawable.ic_heart);
            buttonOne.setTitleBackgroundColor(ContextCompat.getColor(this, R.color.colorAccent));
            fabMenu.addButton(buttonOne);

            buttonTwo = new TitleFAB(this);
            buttonTwo.setTitle("buttonTwo");
            buttonTwo.setImageResource(R.drawable.ic_pencil);
            buttonTwo.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            fabMenu.addButton(buttonTwo);

            buttonThree = new TitleFAB(this);
            buttonThree.setTitle("buttonThree");
            buttonThree.setImageResource(R.drawable.ic_share);
            buttonThree.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            fabMenu.addButton(buttonThree);

            buttonFour = new TitleFAB(this);
            buttonFour.setTitle("buttonFour");
            buttonFour.setImageResource(R.drawable.ic_plus);
            buttonFour.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            fabMenu.addButton(buttonFour);

        } else if (!isCreate && FAB_MENU_STATE != 2) {
            FAB_MENU_STATE = 2;

            if (fabMenu.getButtonsCount() > 1) {
                fabMenu.removeButton(buttonOne);
                fabMenu.removeButton(buttonTwo);
                fabMenu.removeButton(buttonThree);
                fabMenu.removeButton(buttonFour);
            }

            fabMenu.setExpandDirection(FABsMenu.EXPAND_LEFT);

            buttonFive = new TitleFAB(this);
            buttonFive.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            buttonFive.setImageResource(R.drawable.ic_pencil);
            fabMenu.addButton(buttonFive);

            buttonSix = new TitleFAB(this);
            buttonSix.setImageResource(R.drawable.ic_pencil);
            buttonSix.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            fabMenu.addButton(buttonSix);

            buttonSeven = new TitleFAB(this);
            buttonSeven.setImageResource(R.drawable.ic_pencil);
            buttonSeven.setBackgroundColor(ContextCompat.getColor(this, R.color.colorPrimary));
            fabMenu.addButton(buttonSeven);

        }
        fabMenu.expand();
    }
}

and when I clicked fab : 

![screenshot_20170801-120055](https://user-images.githubusercontent.com/12228071/28808832-db061566-76b1-11e7-9728-9c43babf7b5c.jpg)

and when I clicked button:

![screenshot_20170801-120105](https://user-images.githubusercontent.com/12228071/28808839-e23f6062-76b1-11e7-8fc3-5a49264236d3.jpg)

**Comment by jahirfiquitiva** [comment] 2017-08-01 04:16
@RealFeeling 

Thanks for the detailed reply. I will look into it in the next days and hopefully release a fix soon.

Btw, if you could share this project (maybe in a repo), that would be helpful too.

**Comment by RealFeeling** [comment] 2017-08-01 04:37
Thanks . 
I just Edit few code. 
[layout.zip](https://github.com/jahirfiquitiva/FABsMenu/files/1189511/layout.zip)

**Comment by jahirfiquitiva** [comment] 2017-08-01 22:54
Hey @RealFeeling 

Can you please try the using the latest commit and tell me if it fixes the issue?

To do that, just change the `build.gradle` line to this:
`compile 'me.jahirfiquitiva:FABsMenu:495ba96'`

Thanks

**Comment by RealFeeling** [comment] 2017-08-02 06:12
My question has been a perfect solution, thank you!

**Comment by jahirfiquitiva** [comment] 2017-08-02 11:56
@RealFeeling that means the issue is fixed? If so, please close this issue. Thanks

**Closed** 2017-08-03 06:20 UTC
Labels: bug, enhancement, high priority
